### ISSUE TITLE
Option to return `nil` rather than raising an error for invalid UUID

### ISSUE THREAD

**Issue by jhanggi** [nedap/mysql-binuuid-rails#23]
We have places where we are looking up an objected based on a UUID, but the UUID is coming from user input (like a route segment). So for example, let's just say someone is hacking with the URL, we would want this to raise the `ActiveRecord::RecordNotFound` so that we can rescue it and render a 404 page. Instead it raises a `MySQLBinUUID::InvalidUUID` error.

```ruby
# /orders/:id
def show
  @order = Order.find_by!(uuid: params[:id])
end
```

Is there a way to change this behavior so that it would have the default ActiveRecord behavior? I think the `serialize` method also gets used when trying to save, so that should probably continue to raise the error. I'm not sure if there's a good way to distinguish which use case you're in, though.

We can work around this, but we're doing it on a whole bunch of models so it would be nice to find something that would work across the board.

Thanks!

**Comment by markoudev** [comment]
Thanks for creating an issue 😄 

I understand the practical downside of this. It feels a bit strange to have different kinds of rescue's in place while you're only doing a `find_by!`, I agree.

However I'm also thinking they should stay separate things, and an application should be prepared for malformed uuids. I'm not sure how we could detect separate use-cases, but in anyway I would like to keep it as pure and predictable as possible.

I'm thinking out loud here a bit ... Say the `serialize` method would return `nil` in case it's not a valid UUID, what would you expect with `MyThing.create!(uuid: "blah")`?
For number columns I believe that Rails will use `0` if it's not a valid number. So then it create a record with a number set to `0`. If we use that behaviour and return `nil` in case a UUID is not valid, you would potentially create or search for a database record with a `nil` UUID. If your db expects a value to be set, you would get an `ActiveRecord::RecordInvalid` error.

I just tried creating a record where the ID of it is "foo". Rails comes up with a query and creates a record where the id is set to `0`. We could have a discussions whether this is desirable, but that's how it works now. If I run it again, of course, I get an error that id 0 is already in use.

While writing this I don't really mind returning `nil` in case a UUID is malformed. I just have to let it sink in a while because it changes the current behaviour. If you have any additional thoughts please let me know.

**Comment by jhanggi** [comment]
Thanks for the thoughtful response. You're right that its a tricky one. In the case of `create`, I think an exception is probably warranted. Trying to deal with `0` or `null` is probably outside the scope of what you want the gem to do. It's just a little extra work for app developer in the `where` and `find_by` cases. If there were a good way to distinguish whether you're doing a `SELECT` or an `INSERT` during `serialize`, you could do different behavior. I don't know the internals of ActiveRecord, but I'm guessing that's not really possible, or at least worth the added complexity.

We ended up creating a concern that adds a couple AR-like methods so we can share it across our models. We just need to be careful to remember to use these methods rather than the normal ones.

```ruby
class_methods do
  def where_by_uuids(uuids)
      valid_uuids = Array(uuids).select { |uuid| uuid.to_s.delete("-") =~ /\A[[:xdigit:]]{32}\z/ }
      where(uuid: valid_uuids)
  end

  def find_by_uuid(uuid)
    where_by_uuids(uuid).take
  end
```

**Comment by sharmaparesh** [comment]
Hi, sorry to comment on a closed thread. I ran into the similar situation, and have already implemented something similar before actually finding this discussion.

Here in the snippet it is commented that reason for checking UUID validity and raising exception is to avoid SQL injection, it might be a noob question, but could you give me an example how it could be exploited had it not been for this check?

https://github.com/nedap/mysql-binuuid-rails/blob/main/lib/mysql-binuuid/type.rb#L33-L38

```ruby
      # To avoid SQL injection, verify that it looks like a UUID. ActiveRecord
      # does not explicity escape the Binary data type. escaping is implicit as
      # the Binary data type always converts its value to a hex string.
      unless valid_undashed_uuid?(undashed_uuid)
        raise MySQLBinUUID::InvalidUUID, "#{value} is not a valid UUID"
      end

```

**Comment by markoudev** [comment]
There are a few test for this that could help understand what was wrong and why we need this:

https://github.com/nedap/mysql-binuuid-rails/blob/abd7e928c9b3fd54757224aa7219c4ed7a630fc2/test/integration/mysql_integration_test.rb#L108-L124

If we wouldn't check for a valid UUID, the following would happen:

```ruby
> MyUuidModel.find_by(the_uuid: "' OR ''='")

# The query this would perform without checking for a valid UUID would be:
# SELECT `my_uuid_models`.* FROM `my_uuid_models` WHERE `my_uuid_models`.`the_uuid` = x'' OR ''='' LIMIT 1
```

As you can see that it's a perfectly fine query. Instead of `OR ''=''` you can also think of examples that would actually be destructive, like dropping tables:

```ruby
> MyUuidModel.find_by(the_uuid: "'; DROP TABLE users;--")

# Which would yield the following query:
# SELECT `my_uuid_models`.* FROM `my_uuid_models` WHERE `my_uuid_models`.`the_uuid` = x''; DROP TABLE users;-- LIMIT 1
```

This yields two valid queries. You can get really creative with SQL injection in order to read information from the database or alter things. Worst case it could even allow attackers to perform exploits that would give them access to systems.

**Comment by sharmaparesh** [comment]
@markoudev Thank you so much for the details. 🙏
